import type { Metadata } from 'next'
import { Inter, Raleway, Quicksand } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })
const raleway = Raleway({ subsets: ['latin'] })
const quicksand = Quicksand({ subsets: ['vietnamese'], weight:["300", "400", "500"] })
export const metadata: Metadata = {
  title: 'Home - Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
   return (
    <html lang="fr">
      <body className={quicksand.className}>{children}</body>
    </html>
  )
}
